import { TProduct } from "@/types";

/* export type SingleProductType = {
  name: string;
  description: string;
  price: string;
  rating: number;
}; */
/*
export async function getAllProducts() {
  const products = await fetch("http://localhost:8800/products").then((res) =>
    res.json()
  );
  return products;
}
 */


export const products:TProduct[] = [
  {
    id: "1",
    imageId: "1",
    name: "Nike Air Max 270",
    price: 120,
    brand: "nike",
    category: "running",
    gender: "male",
    color: "red",
    rating: 4.5,
    size: "41",
  },
  {
    id: "2",
    imageId: "2",
    name: "Adidas Ultraboost 22",
    price: 150,
    brand: "adidas",
    category: "running",
    gender: "male",
    color: "blue",
    rating: 4.7,
    size: "42",
  },
  {
    id: "3",
    imageId: "3",
    name: "Puma RS-X",
    price: 110,
    brand: "puma",
    category: "casual",
    gender: "male",
    color: "black",
    rating: 4.3,
    size: "40",
  },
  {
    id: "4",
    imageId: "4",
    name: "New Balance 574",
    price: 100,
    brand: "adidas",
    category: "casual",
    gender: "unisex",
    color: "green",
    rating: 4.6,
    size: "43",
  },
  {
    id: "5",
    imageId: "5",
    name: "Asics Gel-Kayano 29",
    price: 160,
    brand: "adidas",
    category: "running",
    gender: "male",
    color: "green",
    rating: 4.8,
    size: "42",
  },
  {
    id: "6",
    imageId: "6",
    name: "Nike Air Force 1",
    price: 130,
    brand: "nike",
    category: "casual",
    gender: "female",
    color: "white",
    rating: 4.9,
    size: "38",
  },
  {
    id: "7",
    imageId: "7",
    name: "Adidas Forum Low",
    price: 110,
    brand: "adidas",
    category: "casual",
    gender: "female",
    color: "red",
    rating: 4.5,
    size: "39",
  },
  {
    id: "8",
    imageId: "8",
    name: "Puma Suede Classic",
    price: 90,
    brand: "puma",
    category: "casual",
    gender: "unisex",
    color: "blue",
    rating: 4.4,
    size: "41",
  },
  {
    id: "9",
    imageId: "9",
    name: "Reebok Nano X3",
    price: 140,
    brand: "reebok",
    category: "training",
    gender: "male",
    color: "black",
    rating: 4.6,
    size: "42",
  },
  {
    id: "10",
    imageId: "10",
    name: "Under Armour HOVR Phantom",
    price: 135,
    brand: "under armour",
    category: "running",
    gender: "male",
    color: "grey",
    rating: 4.7,
    size: "43",
  },
  {
    id: "11",
    imageId: "11",
    name: "Nike ZoomX Vaporfly",
    price: 250,
    brand: "nike",
    category: "running",
    gender: "male",
    color: "white",
    rating: 4.9,
    size: "42",
  },
  {
    id: "12",
    imageId: "12",
    name: "Adidas Gazelle",
    price: 100,
    brand: "adidas",
    category: "casual",
    gender: "female",
    color: "green",
    rating: 4.6,
    size: "38",
  },
  {
    id: "13",
    imageId: "13",
    name: "New Balance 327",
    price: 110,
    brand: "nike",
    category: "casual",
    gender: "unisex",
    color: "white",
    rating: 4.5,
    size: "40",
  },
  {
    id: "14",
    imageId: "14",
    name: "Adidas Novablast 3",
    price: 140,
    brand: "adidas",
    category: "running",
    gender: "female",
    color: "white",
    rating: 4.7,
    size: "39",
  },
  {
    id: "15",
    imageId: "15",
    name: "Puma Future Rider",
    price: 95,
    brand: "puma",
    category: "casual",
    gender: "male",
    color: "yellow",
    rating: 4.3,
    size: "41",
  },
  {
    id: "16",
    imageId: "16",
    name: "Reebok Classic Leather",
    price: 85,
    brand: "reebok",
    category: "casual",
    gender: "female",
    color: "white",
    rating: 4.8,
    size: "38",
  },
  {
    id: "17",
    imageId: "17",
    name: "Under Armour Curry Flow 10",
    price: 160,
    brand: "under armour",
    category: "basketball",
    gender: "male",
    color: "blue",
    rating: 4.7,
    size: "44",
  },
  {
    id: "18",
    imageId: "18",
    name: "Nike Lebron 20",
    price: 200,
    brand: "nike",
    category: "basketball",
    gender: "male",
    color: "red",
    rating: 4.8,
    size: "45",
  },
  {
    id: "19",
    imageId: "19",
    name: "Adidas Harden Vol. 7",
    price: 180,
    brand: "adidas",
    category: "basketball",
    gender: "male",
    color: "black",
    rating: 4.6,
    size: "44",
  },
  {
    id: "20",
    imageId: "20",
    name: "New Balance Fresh Foam",
    price: 130,
    brand: "adidas",
    category: "running",
    gender: "female",
    color: "red",
    rating: 4.7,
    size: "37",
  },
];